require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AllergiesController do

  # This should return the minimal set of attributes required to create a valid
  # Allergy. As you add validations to Allergy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AllergiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all allergies as @allergies" do
      allergy = Allergy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:allergies).should eq([allergy])
    end
  end

  describe "GET show" do
    it "assigns the requested allergy as @allergy" do
      allergy = Allergy.create! valid_attributes
      get :show, {:id => allergy.to_param}, valid_session
      assigns(:allergy).should eq(allergy)
    end
  end

  describe "GET new" do
    it "assigns a new allergy as @allergy" do
      get :new, {}, valid_session
      assigns(:allergy).should be_a_new(Allergy)
    end
  end

  describe "GET edit" do
    it "assigns the requested allergy as @allergy" do
      allergy = Allergy.create! valid_attributes
      get :edit, {:id => allergy.to_param}, valid_session
      assigns(:allergy).should eq(allergy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Allergy" do
        expect {
          post :create, {:allergy => valid_attributes}, valid_session
        }.to change(Allergy, :count).by(1)
      end

      it "assigns a newly created allergy as @allergy" do
        post :create, {:allergy => valid_attributes}, valid_session
        assigns(:allergy).should be_a(Allergy)
        assigns(:allergy).should be_persisted
      end

      it "redirects to the created allergy" do
        post :create, {:allergy => valid_attributes}, valid_session
        response.should redirect_to(Allergy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved allergy as @allergy" do
        # Trigger the behavior that occurs when invalid params are submitted
        Allergy.any_instance.stub(:save).and_return(false)
        post :create, {:allergy => { "name" => "invalid value" }}, valid_session
        assigns(:allergy).should be_a_new(Allergy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Allergy.any_instance.stub(:save).and_return(false)
        post :create, {:allergy => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested allergy" do
        allergy = Allergy.create! valid_attributes
        # Assuming there are no other allergies in the database, this
        # specifies that the Allergy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Allergy.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => allergy.to_param, :allergy => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested allergy as @allergy" do
        allergy = Allergy.create! valid_attributes
        put :update, {:id => allergy.to_param, :allergy => valid_attributes}, valid_session
        assigns(:allergy).should eq(allergy)
      end

      it "redirects to the allergy" do
        allergy = Allergy.create! valid_attributes
        put :update, {:id => allergy.to_param, :allergy => valid_attributes}, valid_session
        response.should redirect_to(allergy)
      end
    end

    describe "with invalid params" do
      it "assigns the allergy as @allergy" do
        allergy = Allergy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Allergy.any_instance.stub(:save).and_return(false)
        put :update, {:id => allergy.to_param, :allergy => { "name" => "invalid value" }}, valid_session
        assigns(:allergy).should eq(allergy)
      end

      it "re-renders the 'edit' template" do
        allergy = Allergy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Allergy.any_instance.stub(:save).and_return(false)
        put :update, {:id => allergy.to_param, :allergy => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested allergy" do
      allergy = Allergy.create! valid_attributes
      expect {
        delete :destroy, {:id => allergy.to_param}, valid_session
      }.to change(Allergy, :count).by(-1)
    end

    it "redirects to the allergies list" do
      allergy = Allergy.create! valid_attributes
      delete :destroy, {:id => allergy.to_param}, valid_session
      response.should redirect_to(allergies_url)
    end
  end

end
