require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MealrecipesController do

  # This should return the minimal set of attributes required to create a valid
  # Mealrecipe. As you add validations to Mealrecipe, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "meal_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MealrecipesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mealrecipes as @mealrecipes" do
      mealrecipe = Mealrecipe.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mealrecipes).should eq([mealrecipe])
    end
  end

  describe "GET show" do
    it "assigns the requested mealrecipe as @mealrecipe" do
      mealrecipe = Mealrecipe.create! valid_attributes
      get :show, {:id => mealrecipe.to_param}, valid_session
      assigns(:mealrecipe).should eq(mealrecipe)
    end
  end

  describe "GET new" do
    it "assigns a new mealrecipe as @mealrecipe" do
      get :new, {}, valid_session
      assigns(:mealrecipe).should be_a_new(Mealrecipe)
    end
  end

  describe "GET edit" do
    it "assigns the requested mealrecipe as @mealrecipe" do
      mealrecipe = Mealrecipe.create! valid_attributes
      get :edit, {:id => mealrecipe.to_param}, valid_session
      assigns(:mealrecipe).should eq(mealrecipe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mealrecipe" do
        expect {
          post :create, {:mealrecipe => valid_attributes}, valid_session
        }.to change(Mealrecipe, :count).by(1)
      end

      it "assigns a newly created mealrecipe as @mealrecipe" do
        post :create, {:mealrecipe => valid_attributes}, valid_session
        assigns(:mealrecipe).should be_a(Mealrecipe)
        assigns(:mealrecipe).should be_persisted
      end

      it "redirects to the created mealrecipe" do
        post :create, {:mealrecipe => valid_attributes}, valid_session
        response.should redirect_to(Mealrecipe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mealrecipe as @mealrecipe" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mealrecipe.any_instance.stub(:save).and_return(false)
        post :create, {:mealrecipe => { "meal_id" => "invalid value" }}, valid_session
        assigns(:mealrecipe).should be_a_new(Mealrecipe)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mealrecipe.any_instance.stub(:save).and_return(false)
        post :create, {:mealrecipe => { "meal_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mealrecipe" do
        mealrecipe = Mealrecipe.create! valid_attributes
        # Assuming there are no other mealrecipes in the database, this
        # specifies that the Mealrecipe created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mealrecipe.any_instance.should_receive(:update_attributes).with({ "meal_id" => "1" })
        put :update, {:id => mealrecipe.to_param, :mealrecipe => { "meal_id" => "1" }}, valid_session
      end

      it "assigns the requested mealrecipe as @mealrecipe" do
        mealrecipe = Mealrecipe.create! valid_attributes
        put :update, {:id => mealrecipe.to_param, :mealrecipe => valid_attributes}, valid_session
        assigns(:mealrecipe).should eq(mealrecipe)
      end

      it "redirects to the mealrecipe" do
        mealrecipe = Mealrecipe.create! valid_attributes
        put :update, {:id => mealrecipe.to_param, :mealrecipe => valid_attributes}, valid_session
        response.should redirect_to(mealrecipe)
      end
    end

    describe "with invalid params" do
      it "assigns the mealrecipe as @mealrecipe" do
        mealrecipe = Mealrecipe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mealrecipe.any_instance.stub(:save).and_return(false)
        put :update, {:id => mealrecipe.to_param, :mealrecipe => { "meal_id" => "invalid value" }}, valid_session
        assigns(:mealrecipe).should eq(mealrecipe)
      end

      it "re-renders the 'edit' template" do
        mealrecipe = Mealrecipe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mealrecipe.any_instance.stub(:save).and_return(false)
        put :update, {:id => mealrecipe.to_param, :mealrecipe => { "meal_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mealrecipe" do
      mealrecipe = Mealrecipe.create! valid_attributes
      expect {
        delete :destroy, {:id => mealrecipe.to_param}, valid_session
      }.to change(Mealrecipe, :count).by(-1)
    end

    it "redirects to the mealrecipes list" do
      mealrecipe = Mealrecipe.create! valid_attributes
      delete :destroy, {:id => mealrecipe.to_param}, valid_session
      response.should redirect_to(mealrecipes_url)
    end
  end

end
