require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MealplansController do

  # This should return the minimal set of attributes required to create a valid
  # Mealplan. As you add validations to Mealplan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "meal_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MealplansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mealplans as @mealplans" do
      mealplan = Mealplan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mealplans).should eq([mealplan])
    end
  end

  describe "GET show" do
    it "assigns the requested mealplan as @mealplan" do
      mealplan = Mealplan.create! valid_attributes
      get :show, {:id => mealplan.to_param}, valid_session
      assigns(:mealplan).should eq(mealplan)
    end
  end

  describe "GET new" do
    it "assigns a new mealplan as @mealplan" do
      get :new, {}, valid_session
      assigns(:mealplan).should be_a_new(Mealplan)
    end
  end

  describe "GET edit" do
    it "assigns the requested mealplan as @mealplan" do
      mealplan = Mealplan.create! valid_attributes
      get :edit, {:id => mealplan.to_param}, valid_session
      assigns(:mealplan).should eq(mealplan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mealplan" do
        expect {
          post :create, {:mealplan => valid_attributes}, valid_session
        }.to change(Mealplan, :count).by(1)
      end

      it "assigns a newly created mealplan as @mealplan" do
        post :create, {:mealplan => valid_attributes}, valid_session
        assigns(:mealplan).should be_a(Mealplan)
        assigns(:mealplan).should be_persisted
      end

      it "redirects to the created mealplan" do
        post :create, {:mealplan => valid_attributes}, valid_session
        response.should redirect_to(Mealplan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mealplan as @mealplan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mealplan.any_instance.stub(:save).and_return(false)
        post :create, {:mealplan => { "meal_id" => "invalid value" }}, valid_session
        assigns(:mealplan).should be_a_new(Mealplan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mealplan.any_instance.stub(:save).and_return(false)
        post :create, {:mealplan => { "meal_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mealplan" do
        mealplan = Mealplan.create! valid_attributes
        # Assuming there are no other mealplans in the database, this
        # specifies that the Mealplan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mealplan.any_instance.should_receive(:update_attributes).with({ "meal_id" => "1" })
        put :update, {:id => mealplan.to_param, :mealplan => { "meal_id" => "1" }}, valid_session
      end

      it "assigns the requested mealplan as @mealplan" do
        mealplan = Mealplan.create! valid_attributes
        put :update, {:id => mealplan.to_param, :mealplan => valid_attributes}, valid_session
        assigns(:mealplan).should eq(mealplan)
      end

      it "redirects to the mealplan" do
        mealplan = Mealplan.create! valid_attributes
        put :update, {:id => mealplan.to_param, :mealplan => valid_attributes}, valid_session
        response.should redirect_to(mealplan)
      end
    end

    describe "with invalid params" do
      it "assigns the mealplan as @mealplan" do
        mealplan = Mealplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mealplan.any_instance.stub(:save).and_return(false)
        put :update, {:id => mealplan.to_param, :mealplan => { "meal_id" => "invalid value" }}, valid_session
        assigns(:mealplan).should eq(mealplan)
      end

      it "re-renders the 'edit' template" do
        mealplan = Mealplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mealplan.any_instance.stub(:save).and_return(false)
        put :update, {:id => mealplan.to_param, :mealplan => { "meal_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mealplan" do
      mealplan = Mealplan.create! valid_attributes
      expect {
        delete :destroy, {:id => mealplan.to_param}, valid_session
      }.to change(Mealplan, :count).by(-1)
    end

    it "redirects to the mealplans list" do
      mealplan = Mealplan.create! valid_attributes
      delete :destroy, {:id => mealplan.to_param}, valid_session
      response.should redirect_to(mealplans_url)
    end
  end

end
